{
	"version": 1543005981,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/muteall-sheet0.png",
		"images/personagens-sheet0.png",
		"images/personagens-sheet1.png",
		"images/personagens-sheet2.png",
		"images/conversas-sheet0.png",
		"images/next-sheet0.png",
		"images/spritefont.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/bggame-sheet0.png",
		"images/bggame-sheet1.png",
		"images/spritefont3.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/spritemenu-sheet0.png",
		"images/barra-sheet0.png",
		"images/bgmenu-sheet0.png",
		"images/bg-sheet0.png",
		"images/btnselecaofase-sheet0.png",
		"images/btnselecaofase-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/logo-sheet0.png",
		"media/medieval-.ogg",
		"media/medieval 2.ogg",
		"media/medieval 4.ogg",
		"media/medieval 5.ogg",
		"media/medieval 6.ogg",
		"media/medieval 3.ogg",
		"media/medieval options.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}